### ISSUE TITLE
Add codespell to github actions

### ISSUE THREAD

**Issue by luzpaz** [DiligentGraphics/DiligentCore#337]
Context: https://github.com/DiligentGraphics/DiligentCore/pull/336#issuecomment-1014785845

Filename: **`.github/workflows/codespell.yml`**

Contents:  
```
# GitHub Action to automate the identification of common misspellings in text files.
# https://github.com/codespell-project/actions-codespell
# https://github.com/codespell-project/codespell

name: Codespell
on: 
  pull_request:

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v12.2

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "$file was changed"
        done

    - uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        ignore_words_file: .github/codespellignore
        skip: ./ThirdParty,*.gltf
        path: ${{ steps.changed-files.outputs.all_changed_files }}
```

Filename: **`.github/codespellignore`**  

Contents:  
```
boundimg
delimeter
delimeters
inout
lod
pres
ser
wser
```
